FROM node:18 as base
RUN corepack enable && corepack prepare pnpm@8.7.1 --activate

FROM base as deps
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN pnpm config set store-dir .pnpm-store
RUN pnpm install

FROM base as builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build

FROM base as runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# COPY .env ./.env
COPY docker-entrypoint.nonlicensed.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
    sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh

ENV NODE_ENV=production
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
